nama_lengkap = input("Nama saya adalah ")
nama_panggil = input("Saya sering di panggil dengan nama ")
prodi = input("saya dari prodi ")
nim = int(input("NIM saya adalah "))
umur = int(input("Saya berumur "))
tinggi = float(input("Tinggi badan saya dengan coma nya adalah "))
asal = input("saya berasal dari sekolah ")
askot = input("dan saya dari kota ")

print ("perkenalkan nama saya", nama_lengkap, ", saya sering di panggil dengan nama", nama_panggil, ", saya berasal dari prodi", prodi, ", NIM saya adalah", nim, "\n" "ajiva saya berumur", umur, ", tinggi badan saya adalah", tinggi, "saya berasal dari sekolah", asal, ", asal kota saya adalah", askot)
print (17)